name: Unit Test Ubuntu

on:
  workflow_dispatch:

jobs:
  unit_test_ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Clone vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh -disableMetrics
      
      - name: Install dependencies
        run: ./vcpkg/vcpkg install gtest cpr libxml2
      
      - name: DEBUG LIST DIRECTORY
        run: |
          pwd
          ls -la
          cd ..
          pwd
          ls -la
          cd ..
          pwd
          ls -la
          cd ..
      
      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/runner/work/WebScraper/WebScraper/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Release
      
      - name: Test project
        run: ctest