name: Unit Test

on:
  workflow_dispatch:

jobs:
  deploy_windows_exe:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Download vcpkg
        run: 'git clone https://github.com/Microsoft/vcpkg.git'
        
      - name: Install vcpkg
        run: '.\vcpkg\bootstrap-vcpkg.bat -disableMetrics'
        
      - name: Install dependencies
        run: '.\vcpkg\vcpkg install gtest cpr libxml2'
        
      - name: Integrate vcpkg
        run: '.\vcpkg\vcpkg integrate install'
        
      - name: Build project
        run: |
          cmake . -DCMAKE_TOOLCHAIN_FILE=D:/a/WebScraper/WebScraper/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Release
          
      - name: Test project
        run: ctest