name: 'Unit Test'

on:
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Clone vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh -disableMetrics
      
      - name: Install libraries
        run: ./vcpkg/vcpkg install gtest cpr libxml2
      
      - name: Get repository code
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Build project
        run: |
          cmake .
          cmake --build . --config Release
      
      - name: Test project
        run: ctest